### ISSUE TITLE
Time and date Format

### ISSUE THREAD

**Issue by Nibeck1309** [chriscareycode/nagiostv-react#12]
Hello, 

Thanks for your job !!!!!!!

It is possible to have an setting for configure time format for Have 12 ou 24 format ?

Best regards

**Comment by chriscareycode** [comment]
Yes I will get this in for 0.4.7 release

**Comment by chriscareycode** [comment]
Actually I want to think about this one more . Maybe it would be best to add support for all international date locales instead of simply adding a 12/24 hour switch. The project uses https://momentjs.com/ - check out the locales at the bottom of that page. Will get out in a future release.

**Comment by arcusbude** [comment]
Hi, is there any configuration possible in 0.4.11 ?

**Comment by Nibeck1309** [comment]
Sorry I don' look the new version.
I test it

**Comment by chriscareycode** [comment]
I have "locales" setting coming in the next version where you can pick a country time/date format, many of which have time in 24h format.  Feature is almost complete.

**Comment by chriscareycode** [comment]
@Nibeck1309 can you give v0.5.0 a try and let me know
https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.5.0

**Comment by chriscareycode** [comment]
This change adds a date format option in settings that controls the date format used in the alerts.
I also added a new Clock up top which is affected by the locales option as well but has it's own format. The clock does not share the same format as alerts since I think some users may like to see date/time in the clock, and some users will just want to see time only. I will release a new update that allows more control over the clock widget soon.

**Comment by Nibeck1309** [comment]
Hello,

With V0.5.1, i can set the good time format.
Thanks for your works

I close this issue
