### ISSUE TITLE
nagiostv 0.5.1 : hide sidebar

### ISSUE THREAD

**Issue by Nibeck1309** [chriscareycode/nagiostv-react#17]
Hello, 

Thanks for your works !!!!!
It's very good webui for nagios.

With this version, it work very well for hide soft alert

With the nagiostv v0.5.1, we have a left sidebar now.
I use nagiostv on tv with frame with 2 nagiostv.

It is possible to hide sidebar ?

In the next release of course.

**Comment by chriscareycode** [comment]
@Nibeck1309  Yes I have a new version in the works where the sidebar is hidden, or I might move it to the bottom. Sidebar takes a lot of space on a mobile phone, as well as the situation you described above. I was trying to clean the design up a bit to make NagiosTV look more professional but had a feeling users would not all like that there by default.

I also realized the hide soft alert did not affect the 24hour chart which is also fixed in the upcoming version.

Thanks for the feedback.

**Comment by chriscareycode** [comment]
@Nibeck1309 https://github.com/chriscareycode/nagiostv-react/releases/tag/v0.5.2

**Comment by Nibeck1309** [comment]
Side bar at bottom is perfect.
I open a new issue for v0.5.2 for filter problem
