### ISSUE TITLE
Nagiostv v0.5.2 filter checkbox problem

### ISSUE THREAD

**Issue by Nibeck1309** [chriscareycode/nagiostv-react#18]
HY,

With the v0.5.2, i have a problem with the filter checkbox for services.
The checkbox don't hide

view attach file
![nagios-Screenshot_20200427_090113](https://user-images.githubusercontent.com/11226474/80343756-be5c8e80-8866-11ea-9678-77cb3e00b2a3.png)

**Comment by chriscareycode** [comment]
Hi Nibeck. I did this change on purpose. But I am up for having a discussion about how it works if you think aesthetically it is unpleasing or distracting.

Previously I would show a "label" widget (which looked the same as the "checkbox" widget without the checkbox) when one of the items such as a WARNING existed, even if it was hidden. This is used as a clue of what is currently hidden on the page without showing each item.

Then when you press "Show Filters" I would show the filters which look the same as the labels except they have a checkbox. So I wanted to try combining them into one. 

My thinking is, if we are already showing a label, then why not allow clicking on it, to toggle the current hidden item easily, and remove need for the extra click on "Show Filters" then to click the checkbox item. 

So the behavior now is the filters are showing automatically **but only for items which are currently active**. Then clicking "Show Filters" behaves like "Show All Filters" where it will show filters regardless if they are currently active or not.

It is also easier for a new user to hide active items currently on the screen since they don't need to know to click "Show Filters" down below.

Hope this makes sense. What are your thoughts on this? Is it just the sight of the checkbox that is displeasing? Would it be better if the checkbox was hidden when "Show Filters" is off?

**Comment by chriscareycode** [comment]
@Nibeck1309  I have noticed the web browser running NagiosTV 0.5.2 lock up after about a day. I'm wondering if you have seen the same? This is using Chrome. In Firefox did not see this yet. 
Let me know if you have noticed any instability. If this is a larger issue then I may need to roll back to a previous version and implement these SOFT alert and date fixes a different way.

**Comment by Nibeck1309** [comment]
> Hi Nibeck. I did this change on purpose. But I am up for having a discussion about how it works if you think aesthetically it is unpleasing or distracting.
> 
> Previously I would show a "label" widget (which looked the same as the "checkbox" widget without the checkbox) when one of the items such as a WARNING existed, even if it was hidden. This is used as a clue of what is currently hidden on the page without showing each item.
> 
> Then when you press "Show Filters" I would show the filters which look the same as the labels except they have a checkbox. So I wanted to try combining them into one.
> 
> My thinking is, if we are already showing a label, then why not allow clicking on it, to toggle the current hidden item easily, and remove need for the extra click on "Show Filters" then to click the checkbox item.
> 
> So the behavior now is the filters are showing automatically **but only for items which are currently active**. Then clicking "Show Filters" behaves like "Show All Filters" where it will show filters regardless if they are currently active or not.
> 
> It is also easier for a new user to hide active items currently on the screen since they don't need to know to click "Show Filters" down below.
> 
> If you have no active UNKNOWN types, but want to hide any future UNKNOWNs, then that is when you would need to click "Show Filters" to see UNKNOWN, and deselect it.
> 
> Hope this makes sense. What are your thoughts on this? Is it just the sight of the checkbox that is displeasing? Would it be better if the checkbox was hidden when "Show Filters" is off?

Hello chris,

I used nagiostv on TV in kiosk mod.
I think it's better to hide checkbox when show filter is off.

**Comment by Nibeck1309** [comment]
> @Nibeck1309 I have noticed the web browser running NagiosTV 0.5.2 lock up after about a day. I'm wondering if you have seen the same? This is using Chrome. In Firefox did not see this yet.
> Let me know if you have noticed any instability. If this is a larger issue then I may need to roll back to a previous version and implement these SOFT alert and date fixes a different way.

Hello Chris,
I use firefox to display nagios tv.
I did not test to leave it open for more than 24 hours.
I would try next week to leave it open for more than 24 hours

**Comment by chriscareycode** [comment]
This will go out with 0.5.3 release
