### ISSUE TITLE
script problem polifill.min.js

### ISSUE THREAD

**Issue by Nibeck1309** [chriscareycode/nagiostv-react#55]
Hello,

I have an issue when I access nagiostv 0.7.5
It seem an problem with this script.
My nagios server don't access to internet and when I access it, I don't acces nagiostv and I juste wait this script timeout
![image](https://user-images.githubusercontent.com/11226474/142178010-f97bd6bf-7ed2-40ab-9559-0a151298e35d.png)

**Comment by chriscareycode** [comment]
That's a script I put in to fix IE 11 support on NagiosTV. Since IE 11 is deprecated now I think it's time that it can be removed.

You can edit index.html in your nagiostv/ folder and delete that line yourself, it will say "for IE 11 polyfill" above it. Then refresh and see if it helps solve the issue.

and I will remove this from a future release. Thanks for the bug report.

**Comment by chriscareycode** [comment]
Published 0.8.2 with a fix for this. Please test and let me know.
